/** Human labels for audit actions (shared by the audit log screen and transaction timeline). */
export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "company.created": "Company created",
  "company.updated": "Company renamed",
  "settings.changed": "Settings changed",
  "auth.login": "Logged in",
  "auth.logout": "Logged out",
  "auth.logout_all": "Logged out of all devices",
  "auth.session_revoked": "Signed out a device",
  "auth.password_changed": "Password changed",
  "auth.password_reset_requested": "Password reset requested",
  "auth.password_reset": "Password reset via email",
  "auth.refresh_token_reuse": "Suspicious session reuse blocked",
  "auth.profile_updated": "Profile updated",
  "user.created": "User created",
  "user.updated": "User updated",
  "user.disabled": "User disabled",
  "user.enabled": "User enabled",
  "user.deleted": "User deleted",
  "user.role_changed": "Role changed",
  "user.password_reset": "Password reset by admin",
  "user.sessions_revoked": "User signed out everywhere",
  "role.created": "Role created",
  "role.updated": "Role updated",
  "role.deleted": "Role deleted",
  "transaction.created": "Created",
  "transaction.edited": "Edited",
  "transaction.submitted": "Submitted",
  "transaction.verified": "Verified",
  "transaction.approved": "Approved",
  "transaction.rejected": "Rejected",
  "transaction.cancelled": "Cancelled",
  "transaction.deleted": "Deleted",
  "category.created": "Category created",
  "category.updated": "Category updated",
  "category.deleted": "Category deleted",
  "cash_account.created": "Cash account created",
  "cash_account.updated": "Cash account updated",
  "attachment.uploaded": "Attachment uploaded",
  "attachment.deleted": "Attachment removed",
  "report.exported": "Report exported",
  "google_sheets.exported": "Exported to Google Sheets",
  "google_sheets.synced": "Synced to Google Sheets",
};

export const AUDIT_ENTITY_LABELS: Record<string, string> = {
  transaction: "Transactions",
  user: "Users",
  role: "Roles",
  category: "Categories",
  cash_account: "Cash accounts",
  company: "Company",
  company_settings: "Settings",
  session: "Sessions",
  report: "Exports",
};

export const auditLabel = (action: string) => AUDIT_ACTION_LABELS[action] ?? action;
